
import java.io.IOException;
import java.io.InputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author hsp97
 */
public class urnaScreen extends javax.swing.JFrame {
    public int vote = 1;
    public String candNumber = "";
    
    public int confirm = 0;
    public int blank = 0;
    public int nulll = 0;
    
    public int joyDivision = 0;
    public int theCure = 0;
    public int bauhaus = 0;
    public int depecheMode = 0;
    
   
    /**
     * Creates new form urnaScreen
     */
    public urnaScreen() {
        initComponents();
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnOne = new javax.swing.JButton();
        btnTwo = new javax.swing.JButton();
        btnThree = new javax.swing.JButton();
        btnFour = new javax.swing.JButton();
        btnFive = new javax.swing.JButton();
        btnSix = new javax.swing.JButton();
        btnSeven = new javax.swing.JButton();
        btnEight = new javax.swing.JButton();
        btnNine = new javax.swing.JButton();
        btnZero = new javax.swing.JButton();
        confirmBtn = new javax.swing.JButton();
        blankBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        firstNum = new javax.swing.JTextField();
        secondNum = new javax.swing.JTextField();
        thirdNum = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        infoTwo = new javax.swing.JTextField();
        infoOne = new javax.swing.JTextField();
        bandPic = new javax.swing.JLabel();
        infoFour = new javax.swing.JTextField();
        infoThree = new javax.swing.JTextField();
        nowPlaying = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        totalJoy = new javax.swing.JTextField();
        totalBau = new javax.swing.JTextField();
        totalMode = new javax.swing.JTextField();
        totalBlank = new javax.swing.JTextField();
        totalNull = new javax.swing.JTextField();
        totalCure = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 255), 2));
        jPanel1.setLayout(null);

        btnOne.setBackground(new java.awt.Color(0, 0, 0));
        btnOne.setFont(new java.awt.Font("TECHNO", 1, 36)); // NOI18N
        btnOne.setForeground(new java.awt.Color(255, 51, 255));
        btnOne.setMnemonic('1');
        btnOne.setToolTipText("Number One");
        btnOne.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 2, true));
        btnOne.setLabel("1");
        btnOne.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOneMouseClicked(evt);
            }
        });
        jPanel1.add(btnOne);
        btnOne.setBounds(10, 10, 90, 60);

        btnTwo.setBackground(new java.awt.Color(0, 0, 0));
        btnTwo.setFont(new java.awt.Font("TECHNO", 1, 36)); // NOI18N
        btnTwo.setForeground(new java.awt.Color(255, 51, 255));
        btnTwo.setMnemonic('2');
        btnTwo.setText("2");
        btnTwo.setToolTipText("Number Two");
        btnTwo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 2, true));
        btnTwo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTwoMouseClicked(evt);
            }
        });
        jPanel1.add(btnTwo);
        btnTwo.setBounds(120, 10, 90, 60);

        btnThree.setBackground(new java.awt.Color(0, 0, 0));
        btnThree.setFont(new java.awt.Font("TECHNO", 1, 36)); // NOI18N
        btnThree.setForeground(new java.awt.Color(255, 51, 255));
        btnThree.setMnemonic('3');
        btnThree.setText("3");
        btnThree.setToolTipText("Number Three");
        btnThree.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 2, true));
        btnThree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThreeMouseClicked(evt);
            }
        });
        jPanel1.add(btnThree);
        btnThree.setBounds(230, 10, 90, 60);

        btnFour.setBackground(new java.awt.Color(0, 0, 0));
        btnFour.setFont(new java.awt.Font("TECHNO", 1, 36)); // NOI18N
        btnFour.setForeground(new java.awt.Color(255, 51, 255));
        btnFour.setMnemonic('4');
        btnFour.setText("4");
        btnFour.setToolTipText("Number Four");
        btnFour.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 2, true));
        btnFour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFourMouseClicked(evt);
            }
        });
        jPanel1.add(btnFour);
        btnFour.setBounds(10, 90, 90, 60);

        btnFive.setBackground(new java.awt.Color(0, 0, 0));
        btnFive.setFont(new java.awt.Font("TECHNO", 1, 36)); // NOI18N
        btnFive.setForeground(new java.awt.Color(255, 51, 255));
        btnFive.setMnemonic('5');
        btnFive.setText("5");
        btnFive.setToolTipText("Number Five");
        btnFive.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 2, true));
        btnFive.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFiveMouseClicked(evt);
            }
        });
        jPanel1.add(btnFive);
        btnFive.setBounds(120, 90, 90, 60);

        btnSix.setBackground(new java.awt.Color(0, 0, 0));
        btnSix.setFont(new java.awt.Font("TECHNO", 1, 36)); // NOI18N
        btnSix.setForeground(new java.awt.Color(255, 51, 255));
        btnSix.setMnemonic('6');
        btnSix.setText("6");
        btnSix.setToolTipText("Number Six");
        btnSix.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 2, true));
        btnSix.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSixMouseClicked(evt);
            }
        });
        jPanel1.add(btnSix);
        btnSix.setBounds(230, 90, 90, 60);

        btnSeven.setBackground(new java.awt.Color(0, 0, 0));
        btnSeven.setFont(new java.awt.Font("TECHNO", 1, 36)); // NOI18N
        btnSeven.setForeground(new java.awt.Color(255, 51, 255));
        btnSeven.setMnemonic('7');
        btnSeven.setText("7");
        btnSeven.setToolTipText("Number Seven");
        btnSeven.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 2, true));
        btnSeven.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSevenMouseClicked(evt);
            }
        });
        jPanel1.add(btnSeven);
        btnSeven.setBounds(10, 170, 90, 60);

        btnEight.setBackground(new java.awt.Color(0, 0, 0));
        btnEight.setFont(new java.awt.Font("TECHNO", 1, 36)); // NOI18N
        btnEight.setForeground(new java.awt.Color(255, 51, 255));
        btnEight.setMnemonic('8');
        btnEight.setText("8");
        btnEight.setToolTipText("Number Eight");
        btnEight.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 2, true));
        btnEight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEightMouseClicked(evt);
            }
        });
        jPanel1.add(btnEight);
        btnEight.setBounds(120, 170, 90, 60);

        btnNine.setBackground(new java.awt.Color(0, 0, 0));
        btnNine.setFont(new java.awt.Font("TECHNO", 1, 36)); // NOI18N
        btnNine.setForeground(new java.awt.Color(255, 51, 255));
        btnNine.setMnemonic('9');
        btnNine.setText("9");
        btnNine.setToolTipText("Number Nine");
        btnNine.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 2, true));
        btnNine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNineMouseClicked(evt);
            }
        });
        jPanel1.add(btnNine);
        btnNine.setBounds(230, 170, 90, 60);

        btnZero.setBackground(new java.awt.Color(0, 0, 0));
        btnZero.setFont(new java.awt.Font("TECHNO", 1, 36)); // NOI18N
        btnZero.setForeground(new java.awt.Color(255, 51, 255));
        btnZero.setMnemonic('0');
        btnZero.setText("0");
        btnZero.setToolTipText("Number Zero");
        btnZero.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 2, true));
        btnZero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnZeroMouseClicked(evt);
            }
        });
        jPanel1.add(btnZero);
        btnZero.setBounds(120, 240, 90, 60);

        confirmBtn.setBackground(new java.awt.Color(255, 51, 255));
        confirmBtn.setFont(new java.awt.Font("TECHNO", 1, 14)); // NOI18N
        confirmBtn.setText("CONFIRM");
        confirmBtn.setToolTipText("Confirm vote");
        confirmBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 255), 2, true));
        confirmBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                confirmBtnMouseClicked(evt);
            }
        });
        jPanel1.add(confirmBtn);
        confirmBtn.setBounds(220, 320, 110, 60);

        blankBtn.setBackground(new java.awt.Color(0, 0, 0));
        blankBtn.setFont(new java.awt.Font("TECHNO-Light", 0, 17)); // NOI18N
        blankBtn.setForeground(new java.awt.Color(255, 51, 255));
        blankBtn.setText("blank");
        blankBtn.setToolTipText("Blank vote");
        blankBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 2, true));
        blankBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                blankBtnMouseClicked(evt);
            }
        });
        jPanel1.add(blankBtn);
        blankBtn.setBounds(10, 320, 90, 60);

        deleteBtn.setBackground(new java.awt.Color(0, 0, 0));
        deleteBtn.setFont(new java.awt.Font("TECHNO-Light", 0, 17)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(255, 51, 255));
        deleteBtn.setText("delete");
        deleteBtn.setToolTipText("Delete the numbers");
        deleteBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 2, true));
        deleteBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteBtnMouseClicked(evt);
            }
        });
        jPanel1.add(deleteBtn);
        deleteBtn.setBounds(120, 320, 90, 60);

        jSeparator1.setBackground(new java.awt.Color(102, 0, 102));
        jSeparator1.setForeground(new java.awt.Color(102, 0, 102));
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(10, 390, 320, 10);

        jLabel12.setFont(new java.awt.Font("Chopsic", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("D I S C L A I M E R");
        jLabel12.setToolTipText("");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(100, 400, 130, 17);

        jLabel18.setFont(new java.awt.Font("Chopsic", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 102, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Made for educational purposes only!");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(10, 420, 320, 15);

        jLabel22.setFont(new java.awt.Font("Chopsic", 0, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(204, 102, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("h.sp97@hotmail.com");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(60, 540, 220, 15);

        jLabel23.setFont(new java.awt.Font("Chopsic", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 255, 255));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Contact");
        jPanel1.add(jLabel23);
        jLabel23.setBounds(40, 520, 270, 17);

        jLabel24.setFont(new java.awt.Font("Chopsic", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Designed and developed by");
        jPanel1.add(jLabel24);
        jLabel24.setBounds(40, 460, 270, 17);

        jLabel25.setFont(new java.awt.Font("Chopsic", 0, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(204, 102, 255));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Henrique");
        jPanel1.add(jLabel25);
        jLabel25.setBounds(60, 480, 220, 15);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(580, 100, 340, 570);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 255), 2));
        jPanel2.setLayout(null);

        firstNum.setBackground(new java.awt.Color(0, 0, 0));
        firstNum.setFont(new java.awt.Font("TECHNO", 1, 40)); // NOI18N
        firstNum.setForeground(new java.awt.Color(255, 51, 255));
        firstNum.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        firstNum.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 3, true));
        jPanel2.add(firstNum);
        firstNum.setBounds(50, 60, 64, 130);

        secondNum.setBackground(new java.awt.Color(0, 0, 0));
        secondNum.setFont(new java.awt.Font("TECHNO", 1, 40)); // NOI18N
        secondNum.setForeground(new java.awt.Color(255, 51, 255));
        secondNum.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        secondNum.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 3, true));
        jPanel2.add(secondNum);
        secondNum.setBounds(140, 60, 64, 130);

        thirdNum.setBackground(new java.awt.Color(0, 0, 0));
        thirdNum.setFont(new java.awt.Font("TECHNO", 1, 40)); // NOI18N
        thirdNum.setForeground(new java.awt.Color(255, 51, 255));
        thirdNum.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        thirdNum.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 3, true));
        jPanel2.add(thirdNum);
        thirdNum.setBounds(230, 60, 64, 130);

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Chopsic", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("USE THE NUMPAD TO INSERT THE NUMBERS!");
        jPanel2.add(jLabel20);
        jLabel20.setBounds(70, 10, 380, 17);

        infoTwo.setBackground(new java.awt.Color(0, 0, 0));
        infoTwo.setFont(new java.awt.Font("Chopsic", 0, 12)); // NOI18N
        infoTwo.setForeground(new java.awt.Color(204, 102, 255));
        infoTwo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        infoTwo.setBorder(null);
        infoTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoTwoActionPerformed(evt);
            }
        });
        jPanel2.add(infoTwo);
        infoTwo.setBounds(10, 240, 410, 20);

        infoOne.setBackground(new java.awt.Color(0, 0, 0));
        infoOne.setFont(new java.awt.Font("Chopsic", 0, 14)); // NOI18N
        infoOne.setForeground(new java.awt.Color(255, 51, 51));
        infoOne.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        infoOne.setBorder(null);
        jPanel2.add(infoOne);
        infoOne.setBounds(10, 210, 410, 30);

        bandPic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(bandPic);
        bandPic.setBounds(350, 30, 200, 200);

        infoFour.setBackground(new java.awt.Color(0, 0, 0));
        infoFour.setFont(new java.awt.Font("Chopsic", 0, 14)); // NOI18N
        infoFour.setForeground(new java.awt.Color(0, 255, 255));
        infoFour.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        infoFour.setBorder(null);
        infoFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoFourActionPerformed(evt);
            }
        });
        jPanel2.add(infoFour);
        infoFour.setBounds(10, 300, 410, 30);

        infoThree.setBackground(new java.awt.Color(0, 0, 0));
        infoThree.setFont(new java.awt.Font("Chopsic", 0, 12)); // NOI18N
        infoThree.setForeground(new java.awt.Color(204, 102, 255));
        infoThree.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        infoThree.setBorder(null);
        jPanel2.add(infoThree);
        infoThree.setBounds(10, 280, 410, 15);

        nowPlaying.setFont(new java.awt.Font("Chopsic", 0, 12)); // NOI18N
        nowPlaying.setForeground(new java.awt.Color(0, 255, 255));
        jPanel2.add(nowPlaying);
        nowPlaying.setBounds(10, 330, 370, 20);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 100, 560, 360);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 255), 2));
        jPanel3.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Chopsic", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("BANDS' NUMBERS");
        jLabel2.setToolTipText("");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(100, 10, 130, 15);

        jLabel4.setFont(new java.awt.Font("Chopsic", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Joy Division:");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(10, 40, 120, 17);

        jLabel5.setFont(new java.awt.Font("Chopsic", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Depeche Mode:");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(10, 160, 140, 17);

        jLabel6.setFont(new java.awt.Font("Chopsic", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("The Cure:");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(10, 80, 100, 17);

        jLabel3.setFont(new java.awt.Font("Chopsic", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Bauhaus:");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(10, 120, 90, 17);

        jLabel7.setFont(new java.awt.Font("Chopsic", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 102, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("202");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(260, 40, 36, 17);

        jLabel8.setFont(new java.awt.Font("Chopsic", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 102, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("303");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(260, 80, 36, 17);

        jLabel9.setFont(new java.awt.Font("Chopsic", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 102, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("404");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(260, 120, 36, 17);

        jLabel10.setFont(new java.awt.Font("Chopsic", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 102, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("505");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(260, 160, 36, 17);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(10, 470, 300, 200);

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255), 2));
        jPanel4.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Chopsic", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 51, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("LIVE COUNTER");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(80, 10, 110, 15);

        jLabel13.setFont(new java.awt.Font("Chopsic", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("Joy Division");
        jPanel4.add(jLabel13);
        jLabel13.setBounds(10, 30, 91, 15);

        jLabel14.setFont(new java.awt.Font("Chopsic", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("The Cure");
        jPanel4.add(jLabel14);
        jLabel14.setBounds(10, 60, 80, 15);

        jLabel15.setFont(new java.awt.Font("Chopsic", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("Bauhaus");
        jPanel4.add(jLabel15);
        jLabel15.setBounds(10, 90, 80, 15);

        jLabel16.setFont(new java.awt.Font("Chopsic", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("Depeche Mode");
        jPanel4.add(jLabel16);
        jLabel16.setBounds(10, 120, 120, 15);

        jLabel17.setFont(new java.awt.Font("Chopsic", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("Blank");
        jPanel4.add(jLabel17);
        jLabel17.setBounds(10, 150, 50, 15);

        jLabel19.setFont(new java.awt.Font("Chopsic", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel19.setText("NULL");
        jPanel4.add(jLabel19);
        jLabel19.setBounds(10, 180, 43, 16);

        totalJoy.setBackground(new java.awt.Color(0, 0, 0));
        totalJoy.setFont(new java.awt.Font("Chopsic", 0, 12)); // NOI18N
        totalJoy.setForeground(new java.awt.Color(255, 51, 255));
        totalJoy.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totalJoy.setBorder(null);
        jPanel4.add(totalJoy);
        totalJoy.setBounds(160, 30, 80, 10);

        totalBau.setBackground(new java.awt.Color(0, 0, 0));
        totalBau.setFont(new java.awt.Font("Chopsic", 0, 12)); // NOI18N
        totalBau.setForeground(new java.awt.Color(255, 51, 255));
        totalBau.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totalBau.setBorder(null);
        jPanel4.add(totalBau);
        totalBau.setBounds(160, 90, 80, 10);

        totalMode.setBackground(new java.awt.Color(0, 0, 0));
        totalMode.setFont(new java.awt.Font("Chopsic", 0, 12)); // NOI18N
        totalMode.setForeground(new java.awt.Color(255, 51, 255));
        totalMode.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totalMode.setBorder(null);
        jPanel4.add(totalMode);
        totalMode.setBounds(160, 120, 80, 10);

        totalBlank.setBackground(new java.awt.Color(0, 0, 0));
        totalBlank.setFont(new java.awt.Font("Chopsic", 0, 12)); // NOI18N
        totalBlank.setForeground(new java.awt.Color(255, 51, 255));
        totalBlank.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totalBlank.setBorder(null);
        jPanel4.add(totalBlank);
        totalBlank.setBounds(160, 150, 80, 10);

        totalNull.setBackground(new java.awt.Color(0, 0, 0));
        totalNull.setFont(new java.awt.Font("Chopsic", 0, 12)); // NOI18N
        totalNull.setForeground(new java.awt.Color(255, 51, 255));
        totalNull.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totalNull.setBorder(null);
        jPanel4.add(totalNull);
        totalNull.setBounds(160, 180, 80, 10);

        totalCure.setBackground(new java.awt.Color(0, 0, 0));
        totalCure.setFont(new java.awt.Font("Chopsic", 0, 12)); // NOI18N
        totalCure.setForeground(new java.awt.Color(255, 51, 255));
        totalCure.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totalCure.setBorder(null);
        jPanel4.add(totalCure);
        totalCure.setBounds(160, 60, 80, 10);

        jSeparator2.setBackground(new java.awt.Color(0, 102, 204));
        jSeparator2.setForeground(new java.awt.Color(0, 255, 255));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel4.add(jSeparator2);
        jSeparator2.setBounds(140, 30, 10, 160);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(320, 470, 250, 200);

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 255), 2));
        jPanel5.setLayout(null);

        jLabel21.setFont(new java.awt.Font("Chopsic", 0, 20)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(204, 102, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("THE GOTH URN");
        jPanel5.add(jLabel21);
        jLabel21.setBounds(360, 10, 180, 24);

        jLabel1.setFont(new java.awt.Font("Chopsic", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Vote for the \"BEST GOTH BAND OF THE WORLD\"!");
        jLabel1.setToolTipText("");
        jPanel5.add(jLabel1);
        jLabel1.setBounds(220, 40, 490, 30);

        getContentPane().add(jPanel5);
        jPanel5.setBounds(10, 10, 910, 80);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnZeroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnZeroMouseClicked
        if (confirm == 0) {
            if (vote == 1) {
                vote++;
                candNumber += 0;
                firstNum.setText("0");
            } else if (vote == 2){
                vote++;
                candNumber += 0;
                secondNum.setText("0");
            } else if (vote == 3) {
                vote++;
                candNumber += 0;
                thirdNum.setText("0");
                
                switch (candNumber) {
                    case "202":
                        infoOne.setText("YOU PICKED JOY DIVISION!");
                        infoTwo.setText("PRESS CONFIRM TO VOTE OR DELETE TO RESET");
                        infoThree.setText("OR BLANK TO VOTE BLANK");
                        bandPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("joy.jpg")));
                        nowPlaying.setText("PLAYING: JOY DIVISION - LOVE WILL TEAR US APART");
                        
                        String JD = "joydivision.wav";
                        InputStream input = getClass().getResourceAsStream(JD);
                        Clip oClip = null;
                        try {
                            oClip = AudioSystem.getClip();
                        } 
                        catch (LineUnavailableException ex) {
                            Logger.getLogger(urnaScreen.class.getName()).log(Level.SEVERE, null, ex);
                        }
                         AudioInputStream audioInput = null;
                        try {
                            audioInput = AudioSystem.getAudioInputStream(input);
                        } 
                        catch (UnsupportedAudioFileException ex) {
                            Logger.getLogger(urnaScreen.class.getName()).log(Level.SEVERE, null, ex);
                        } 
                        catch (IOException ex) {
                            Logger.getLogger(urnaScreen.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        try {
                            oClip.open(audioInput);
                        } 
                        catch (LineUnavailableException ex) {
                            Logger.getLogger(urnaScreen.class.getName()).log(Level.SEVERE, null, ex);
                        } 
                        catch (IOException ex) {
                            Logger.getLogger(urnaScreen.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        oClip.loop(0);
                        
                        break;
                    case "303":
                        infoOne.setText("YOU PICKED THE CURE!");
                        infoTwo.setText("PRESS CONFIRM TO VOTE OR DELETE TO RESET");
                        infoThree.setText("OR BLANK TO VOTE BLANK");
                        bandPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("thecure.png")));
                        nowPlaying.setText("PLAYING: THE CURE - JUST LIKE HEAVEN");
                        
                        String TC = "thecure.wav";
                        InputStream inputTwo = getClass().getResourceAsStream(TC);
                        Clip oClipTwo = null;
                        try {
                            oClipTwo = AudioSystem.getClip();
                        } 
                        catch (LineUnavailableException ex) {
                            Logger.getLogger(urnaScreen.class.getName()).log(Level.SEVERE, null, ex);
                        }
                         AudioInputStream audioInputTwo = null;
                        try {
                            audioInputTwo = AudioSystem.getAudioInputStream(inputTwo);
                        } 
                        catch (UnsupportedAudioFileException ex) {
                            Logger.getLogger(urnaScreen.class.getName()).log(Level.SEVERE, null, ex);
                        } 
                        catch (IOException ex) {
                            Logger.getLogger(urnaScreen.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        try {
                            oClipTwo.open(audioInputTwo);
                        } 
                        catch (LineUnavailableException ex) {
                            Logger.getLogger(urnaScreen.class.getName()).log(Level.SEVERE, null, ex);
                        } 
                        catch (IOException ex) {
                            Logger.getLogger(urnaScreen.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        oClipTwo.loop(0);
                        
                        break;
                    case "404":
                        infoOne.setText("YOU PICKED BAUHAUS");
                        infoTwo.setText("PRESS CONFIRM TO VOTE OR DELETE TO RESET");
                        infoThree.setText("OR BLANK TO VOTE BLANK");
                        bandPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("bauhaus.jpg")));
                        nowPlaying.setText("PLAYING: BAUHAUS - SHE'S IN PARTIES");
                        
                        String BH = "bauhaus.wav";
                        InputStream inputThree = getClass().getResourceAsStream(BH);
                        Clip oClipThree = null;
                        try {
                            oClipThree = AudioSystem.getClip();
                        } 
                        catch (LineUnavailableException ex) {
                            Logger.getLogger(urnaScreen.class.getName()).log(Level.SEVERE, null, ex);
                        }
                         AudioInputStream audioInputThree = null;
                        try {
                            audioInputThree = AudioSystem.getAudioInputStream(inputThree);
                        } 
                        catch (UnsupportedAudioFileException ex) {
                            Logger.getLogger(urnaScreen.class.getName()).log(Level.SEVERE, null, ex);
                        } 
                        catch (IOException ex) {
                            Logger.getLogger(urnaScreen.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        try {
                            oClipThree.open(audioInputThree);
                        } 
                        catch (LineUnavailableException ex) {
                            Logger.getLogger(urnaScreen.class.getName()).log(Level.SEVERE, null, ex);
                        } 
                        catch (IOException ex) {
                            Logger.getLogger(urnaScreen.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        oClipThree.loop(0);
                        
                        break;
                    case "505":
                        infoOne.setText("YOU PICKED DEPECHE MODE");
                        infoTwo.setText("PRESS CONFIRM TO VOTE OR DELETE TO RESET");
                        infoThree.setText("OR BLANK TO VOTE BLANK");
                        bandPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("depeche.jpg")));
                        nowPlaying.setText("PLAYING: DEPECHE MODE - ENJOY THE SILENCE");
                        
                        String DP = "depeche.wav";
                        InputStream inputFour = getClass().getResourceAsStream(DP);
                        Clip oClipFour = null;
                        try {
                            oClipFour = AudioSystem.getClip();
                        } 
                        catch (LineUnavailableException ex) {
                            Logger.getLogger(urnaScreen.class.getName()).log(Level.SEVERE, null, ex);
                        }
                         AudioInputStream audioInputFour = null;
                        try {
                            audioInputFour = AudioSystem.getAudioInputStream(inputFour);
                        } 
                        catch (UnsupportedAudioFileException ex) {
                            Logger.getLogger(urnaScreen.class.getName()).log(Level.SEVERE, null, ex);
                        } 
                        catch (IOException ex) {
                            Logger.getLogger(urnaScreen.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        try {
                            oClipFour.open(audioInputFour);
                        } 
                        catch (LineUnavailableException ex) {
                            Logger.getLogger(urnaScreen.class.getName()).log(Level.SEVERE, null, ex);
                        } 
                        catch (IOException ex) {
                            Logger.getLogger(urnaScreen.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        oClipFour.loop(0);
                        
                        break;
                    default:
                        infoThree.setText("NO BANDS REGISTERED WITH THIS NUMBER!");
                        infoFour.setText("CLICK CONFIRM FOR NULL-VOTE");
                }
                        
            } else {
                infoThree.setText("BANDS ONLY HAVE THREE NUMBERS!");
                infoFour.setText("CLICK DELETE TO INSERT NUMBERS AGAIN!");
            }
        }
    }//GEN-LAST:event_btnZeroMouseClicked

    private void btnOneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOneMouseClicked
        if (confirm == 0) {
            if (vote == 1) {
                vote++;
                candNumber += 1;
                firstNum.setText("1");
            } else if (vote == 2){
                vote++;
                candNumber += 1;
                secondNum.setText("1");
            } else if (vote == 3) {
                vote++;
                candNumber += 1;
                thirdNum.setText("1");
                
                switch (candNumber) {
                    case "202":
                        infoOne.setText("YOU PICKED JOY DIVISION!");
                        break;
                    case "303":
                        infoOne.setText("YOU PICKED THE CURE!");
                        break;
                    case "404":
                        infoOne.setText("YOU PICKED BAUHAUS");
                        break;
                    case "505":
                        infoOne.setText("YOU PICKED DEPECHE MODE");
                        break;
                    default:
                        infoThree.setText("NO BANDS REGISTERED WITH THIS NUMBER!");
                        infoFour.setText("CLICK CONFIRM FOR NULL-VOTE");
                }
                
            } else {
                infoThree.setText("BANDS ONLY HAVE THREE NUMBERS!");
                infoFour.setText("CLICK DELETE TO INSERT NUMBERS AGAIN!");
            }
        }
    }//GEN-LAST:event_btnOneMouseClicked

    private void btnTwoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTwoMouseClicked
        if (confirm == 0) {
            if (vote == 1) {
                vote++;
                candNumber += 2;
                firstNum.setText("2");
            } else if (vote == 2){
                vote++;
                candNumber += 2;
                secondNum.setText("2");
            } else if (vote == 3) {
                vote++;
                candNumber += 2;
                thirdNum.setText("2");
                
                switch (candNumber) {
                    case "202":
                        infoOne.setText("YOU PICKED JOY DIVISION!");
                        infoTwo.setText("PRESS CONFIRM TO VOTE OR DELETE TO RESET");
                        infoThree.setText("OR BLANK TO VOTE BLANK");
                        bandPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("joy.jpg")));
                        nowPlaying.setText("PLAYING: JOY DIVISION - LOVE WILL TEAR US APART");
                        
                        String JD = "joydivision.wav";
                        InputStream input = getClass().getResourceAsStream(JD);
                        Clip oClip = null;
                        try {
                            oClip = AudioSystem.getClip();
                        } 
                        catch (LineUnavailableException ex) {
                            Logger.getLogger(urnaScreen.class.getName()).log(Level.SEVERE, null, ex);
                        }
                         AudioInputStream audioInput = null;
                        try {
                            audioInput = AudioSystem.getAudioInputStream(input);
                        } 
                        catch (UnsupportedAudioFileException ex) {
                            Logger.getLogger(urnaScreen.class.getName()).log(Level.SEVERE, null, ex);
                        } 
                        catch (IOException ex) {
                            Logger.getLogger(urnaScreen.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        try {
                            oClip.open(audioInput);
                        } 
                        catch (LineUnavailableException ex) {
                            Logger.getLogger(urnaScreen.class.getName()).log(Level.SEVERE, null, ex);
                        } 
                        catch (IOException ex) {
                            Logger.getLogger(urnaScreen.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        oClip.loop(0);
                        
                        break;
                    case "303":
                        infoOne.setText("YOU PICKED THE CURE!");
                        break;
                    case "404":
                        infoOne.setText("YOU PICKED BAUHAUS");
                        break;
                    case "505":
                        infoOne.setText("YOU PICKED DEPECHE MODE");
                        break;
                    default:
                        infoThree.setText("NO BANDS REGISTERED WITH THIS NUMBER!");
                        infoFour.setText("CLICK CONFIRM FOR NULL-VOTE");
                }
                
            } else {
                infoThree.setText("BANDS ONLY HAVE THREE NUMBERS!");
                infoFour.setText("CLICK DELETE TO INSERT NUMBERS AGAIN!");
            }
        }
    }//GEN-LAST:event_btnTwoMouseClicked

    private void btnThreeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThreeMouseClicked
        if (confirm == 0) {
            if (vote == 1) {
                vote++;
                candNumber += 3;
                firstNum.setText("3");
            } else if (vote == 2){
                vote++;
                candNumber += 3;
                secondNum.setText("3");
            } else if (vote == 3) {
                vote++;
                candNumber += 3;
                thirdNum.setText("3");
                
                switch (candNumber) {
                    case "202":
                        infoOne.setText("YOU PICKED JOY DIVISION!");
                        break;
                    case "303":
                        infoOne.setText("YOU PICKED THE CURE!");
                        infoTwo.setText("PRESS CONFIRM TO VOTE OR DELETE TO RESET");
                        infoThree.setText("OR BLANK TO VOTE BLANK");
                        bandPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("thecure.png")));
                        nowPlaying.setText("PLAYING: THE CURE - JUST LIKE HEAVEN");
                        
                        String TC = "thecure.wav";
                        InputStream inputTwo = getClass().getResourceAsStream(TC);
                        Clip oClipTwo = null;
                        try {
                            oClipTwo = AudioSystem.getClip();
                        } 
                        catch (LineUnavailableException ex) {
                            Logger.getLogger(urnaScreen.class.getName()).log(Level.SEVERE, null, ex);
                        }
                         AudioInputStream audioInputTwo = null;
                        try {
                            audioInputTwo = AudioSystem.getAudioInputStream(inputTwo);
                        } 
                        catch (UnsupportedAudioFileException ex) {
                            Logger.getLogger(urnaScreen.class.getName()).log(Level.SEVERE, null, ex);
                        } 
                        catch (IOException ex) {
                            Logger.getLogger(urnaScreen.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        try {
                            oClipTwo.open(audioInputTwo);
                        } 
                        catch (LineUnavailableException ex) {
                            Logger.getLogger(urnaScreen.class.getName()).log(Level.SEVERE, null, ex);
                        } 
                        catch (IOException ex) {
                            Logger.getLogger(urnaScreen.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        oClipTwo.loop(0);
                        
                        break;
                    case "404":
                        infoOne.setText("YOU PICKED BAUHAUS");
                        break;
                    case "505":
                        infoOne.setText("YOU PICKED DEPECHE MODE");
                        break;
                    default:
                        infoThree.setText("NO BANDS REGISTERED WITH THIS NUMBER!");
                        infoFour.setText("CLICK CONFIRM FOR NULL-VOTE");
                }
                
            } else {
                infoThree.setText("BANDS ONLY HAVE THREE NUMBERS!");
                infoFour.setText("CLICK DELETE TO INSERT NUMBERS AGAIN!");
            }
        }
    }//GEN-LAST:event_btnThreeMouseClicked

    private void btnFourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFourMouseClicked
        if (confirm == 0) {
            if (vote == 1) {
                vote++;
                candNumber += 4;
                firstNum.setText("4");
            } else if (vote == 2){
                vote++;
                candNumber += 4;
                secondNum.setText("4");
            } else if (vote == 3) {
                vote++;
                candNumber += 4;
                thirdNum.setText("4");
                
                switch (candNumber) {
                    case "202":
                        infoOne.setText("YOU PICKED JOY DIVISION!");
                        break;
                    case "303":
                        infoOne.setText("YOU PICKED THE CURE!");
                        break;
                    case "404":
                        infoOne.setText("YOU PICKED BAUHAUS");
                        infoTwo.setText("PRESS CONFIRM TO VOTE OR DELETE TO RESET");
                        infoThree.setText("OR BLANK TO VOTE BLANK");
                        bandPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("bauhaus.jpg")));
                        nowPlaying.setText("PLAYING: BAUHAUS - SHE'S IN PARTIES");
                        
                        String BH = "bauhaus.wav";
                        InputStream inputThree = getClass().getResourceAsStream(BH);
                        Clip oClipThree = null;
                        try {
                            oClipThree = AudioSystem.getClip();
                        } 
                        catch (LineUnavailableException ex) {
                            Logger.getLogger(urnaScreen.class.getName()).log(Level.SEVERE, null, ex);
                        }
                         AudioInputStream audioInputThree = null;
                        try {
                            audioInputThree = AudioSystem.getAudioInputStream(inputThree);
                        } 
                        catch (UnsupportedAudioFileException ex) {
                            Logger.getLogger(urnaScreen.class.getName()).log(Level.SEVERE, null, ex);
                        } 
                        catch (IOException ex) {
                            Logger.getLogger(urnaScreen.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        try {
                            oClipThree.open(audioInputThree);
                        } 
                        catch (LineUnavailableException ex) {
                            Logger.getLogger(urnaScreen.class.getName()).log(Level.SEVERE, null, ex);
                        } 
                        catch (IOException ex) {
                            Logger.getLogger(urnaScreen.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        oClipThree.loop(0);
                        break;
                    case "505":
                        infoOne.setText("YOU PICKED DEPECHE MODE");
                        break;
                    default:
                        infoThree.setText("NO BANDS REGISTERED WITH THIS NUMBER!");
                        infoFour.setText("CLICK CONFIRM FOR NULL-VOTE");
                }
                
            } else {
                infoThree.setText("BANDS ONLY HAVE THREE NUMBERS!");
                infoFour.setText("CLICK DELETE TO INSERT NUMBERS AGAIN!");
            }
        }
    }//GEN-LAST:event_btnFourMouseClicked

    private void btnFiveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFiveMouseClicked
        if (confirm == 0) {
            if (vote == 1) {
                vote++;
                candNumber += 5;
                firstNum.setText("5");
            } else if (vote == 2){
                vote++;
                candNumber += 5;
                secondNum.setText("5");
            } else if (vote == 3) {
                vote++;
                candNumber += 5;
                thirdNum.setText("5");
                
               switch (candNumber) {
                    case "202":
                        infoOne.setText("YOU PICKED JOY DIVISION!");
                        break;
                    case "303":
                        infoOne.setText("YOU PICKED THE CURE!");
                        break;
                    case "404":
                        infoOne.setText("YOU PICKED BAUHAUS");
                        break;
                    case "505":
                        infoOne.setText("YOU PICKED DEPECHE MODE");
                        infoTwo.setText("PRESS CONFIRM TO VOTE, DELETE TO RESET");
                        infoThree.setText("OR BLANK TO VOTE BLANK");
                        bandPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("depeche.jpg")));
                        nowPlaying.setText("PLAYING: DEPECHE MODE - ENJOY THE SILENCE");
                        
                        String DP = "depeche.wav";
                        InputStream inputFour = getClass().getResourceAsStream(DP);
                        Clip oClipFour = null;
                        try {
                            oClipFour = AudioSystem.getClip();
                        } 
                        catch (LineUnavailableException ex) {
                            Logger.getLogger(urnaScreen.class.getName()).log(Level.SEVERE, null, ex);
                        }
                         AudioInputStream audioInputFour = null;
                        try {
                            audioInputFour = AudioSystem.getAudioInputStream(inputFour);
                        } 
                        catch (UnsupportedAudioFileException ex) {
                            Logger.getLogger(urnaScreen.class.getName()).log(Level.SEVERE, null, ex);
                        } 
                        catch (IOException ex) {
                            Logger.getLogger(urnaScreen.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        try {
                            oClipFour.open(audioInputFour);
                        } 
                        catch (LineUnavailableException ex) {
                            Logger.getLogger(urnaScreen.class.getName()).log(Level.SEVERE, null, ex);
                        } 
                        catch (IOException ex) {
                            Logger.getLogger(urnaScreen.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        oClipFour.loop(0);
                        
                        break;
                    default:
                        infoThree.setText("NO BANDS REGISTERED WITH THIS NUMBER!");
                        infoFour.setText("CLICK CONFIRM FOR NULL-VOTE");
                }
                
            } else {
                infoThree.setText("BANDS ONLY HAVE THREE NUMBERS!");
                infoFour.setText("CLICK DELETE TO INSERT NUMBERS AGAIN!");
            }
        }
    }//GEN-LAST:event_btnFiveMouseClicked

    private void btnSixMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSixMouseClicked
        if (confirm == 0) {
            if (vote == 1) {
                vote++;
                candNumber += 6;
                firstNum.setText("6");
            } else if (vote == 2){
                vote++;
                candNumber += 6;
                secondNum.setText("6");
            } else if (vote == 3) {
                vote++;
                candNumber += 6;
                thirdNum.setText("6");
                
                switch (candNumber) {
                    case "202":
                        infoOne.setText("YOU PICKED JOY DIVISION!");
                        break;
                    case "303":
                        infoOne.setText("YOU PICKED THE CURE!");
                        break;
                    case "404":
                        infoOne.setText("YOU PICKED BAUHAUS");
                        break;
                    case "505":
                        infoOne.setText("YOU PICKED DEPECHE MODE");
                        break;
                    default:
                        infoThree.setText("NO BANDS REGISTERED WITH THIS NUMBER!");
                        infoFour.setText("CLICK CONFIRM FOR NULL-VOTE");
                }
                
            } else {
                infoThree.setText("BANDS ONLY HAVE THREE NUMBERS!");
                infoFour.setText("CLICK DELETE TO INSERT NUMBERS AGAIN!");
            }
        }
    }//GEN-LAST:event_btnSixMouseClicked

    private void btnSevenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSevenMouseClicked
        if (confirm == 0) {
            if (vote == 1) {
                vote++;
                candNumber += 7;
                firstNum.setText("7");
            } else if (vote == 2){
                vote++;
                candNumber += 7;
                secondNum.setText("7");
            } else if (vote == 3) {
                vote++;
                candNumber += 7;
                thirdNum.setText("7");
                
                switch (candNumber) {
                    case "202":
                        infoOne.setText("YOU PICKED JOY DIVISION!");
                        break;
                    case "303":
                        infoOne.setText("YOU PICKED THE CURE!");
                        break;
                    case "404":
                        infoOne.setText("YOU PICKED BAUHAUS");
                        break;
                    case "505":
                        infoOne.setText("YOU PICKED DEPECHE MODE");
                        break;
                    default:
                        infoThree.setText("NO BANDS REGISTERED WITH THIS NUMBER!");
                        infoFour.setText("CLICK CONFIRM FOR NULL-VOTE");
                }
                
            } else {
                infoThree.setText("BANDS ONLY HAVE THREE NUMBERS!");
                infoFour.setText("CLICK DELETE TO INSERT NUMBERS AGAIN!");
            }
        }
    }//GEN-LAST:event_btnSevenMouseClicked

    private void btnEightMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEightMouseClicked
        if (confirm == 0) {
            if (vote == 1) {
                vote++;
                candNumber += 8;
                firstNum.setText("8");
            } else if (vote == 2){
                vote++;
                candNumber += 8;
                secondNum.setText("8");
            } else if (vote == 3) {
                vote++;
                candNumber += 8;
                thirdNum.setText("8");
                
                switch (candNumber) {
                    case "202":
                        infoOne.setText("YOU PICKED JOY DIVISION!");
                        break;
                    case "303":
                        infoOne.setText("YOU PICKED THE CURE!");
                        break;
                    case "404":
                        infoOne.setText("YOU PICKED BAUHAUS");
                        break;
                    case "505":
                        infoOne.setText("YOU PICKED DEPECHE MODE");
                        break;
                    default:
                        infoThree.setText("NO BANDS REGISTERED WITH THIS NUMBER!");
                        infoFour.setText("CLICK CONFIRM FOR NULL-VOTE");
                }
               
            } else {
                infoThree.setText("BANDS ONLY HAVE THREE NUMBERS!");
                infoFour.setText("CLICK DELETE TO INSERT NUMBERS AGAIN!");
            }
        }
    }//GEN-LAST:event_btnEightMouseClicked

    private void btnNineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNineMouseClicked
        if (confirm == 0) {
            if (vote == 1) {
                vote++;
                candNumber += 9;
                firstNum.setText("9");
            } else if (vote == 2){
                vote++;
                candNumber += 9;
                secondNum.setText("9");
            } else if (vote == 3) {
                vote++;
                candNumber += 9;
                thirdNum.setText("9");
                
                switch (candNumber) {
                    case "202":
                        infoOne.setText("YOU PICKED JOY DIVISION!");
                        break;
                    case "303":
                        infoOne.setText("YOU PICKED THE CURE!");
                        break;
                    case "404":
                        infoOne.setText("YOU PICKED BAUHAUS");
                        break;
                    case "505":
                        infoOne.setText("YOU PICKED DEPECHE MODE");
                        break;
                    default:
                        infoThree.setText("NO BANDS REGISTERED WITH THIS NUMBER!");
                        infoFour.setText("CLICK CONFIRM FOR NULL-VOTE");
                }
                
            } else {
                infoThree.setText("BANDS ONLY HAVE THREE NUMBERS!");
                infoFour.setText("CLICK DELETE TO INSERT NUMBERS AGAIN!");
            }
        }
    }//GEN-LAST:event_btnNineMouseClicked

    private void infoFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoFourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_infoFourActionPerformed

    private void deleteBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBtnMouseClicked
        confirm = 0;
        deleteBtn.setText("delete");
        if (confirm == 0) {
            vote = 1;
            candNumber = "";
            firstNum.setText("");
            secondNum.setText("");
            thirdNum.setText("");
            infoOne.setText("");
            infoTwo.setText("");
            infoThree.setText("");
            infoFour.setText("");
            bandPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
            nowPlaying.setText("");
        }
    }//GEN-LAST:event_deleteBtnMouseClicked

    private void infoTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoTwoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_infoTwoActionPerformed

    private void confirmBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmBtnMouseClicked
        confirm = 1;
        infoTwo.setText("YOUR VOTE HAS BEEN COMPUTED");
        infoThree.setText("THANKS FOR PARTICIPATING");
        infoFour.setText("CLICK VA TO VOTE AGAIN");
        deleteBtn.setText("VA");
        
        
        if (confirm == 1) {
            switch (candNumber) {
                case "202":
                    joyDivision++;
                    totalJoy.setText(Integer.toString(joyDivision));
                    break;
                case "303":
                    theCure++;
                    totalCure.setText(Integer.toString(theCure));
                    break;
                case "404":
                    bauhaus++;
                    totalBau.setText(Integer.toString(bauhaus));
                    break;
                case "505":
                    depecheMode++;
                    totalMode.setText(Integer.toString(depecheMode));
                    break;
                default:
                    nulll++;
                    totalNull.setText(Integer.toString(nulll));
            }
        }
    }//GEN-LAST:event_confirmBtnMouseClicked

    private void blankBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_blankBtnMouseClicked
        confirm = 1;
        infoTwo.setText("YOUR VOTE HAS BEEN COMPUTED");
        infoThree.setText("THANKS FOR PARTICIPATING");
        infoFour.setText("CLICK VA TO VOTE AGAIN");
        deleteBtn.setText("VA");
        
        if (confirm == 1) {
            blank++;
            totalBlank.setText(Integer.toString(blank));
        }
    }//GEN-LAST:event_blankBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(urnaScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(urnaScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(urnaScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(urnaScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new urnaScreen().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bandPic;
    private javax.swing.JButton blankBtn;
    private javax.swing.JButton btnEight;
    private javax.swing.JButton btnFive;
    private javax.swing.JButton btnFour;
    private javax.swing.JButton btnNine;
    private javax.swing.JButton btnOne;
    private javax.swing.JButton btnSeven;
    private javax.swing.JButton btnSix;
    private javax.swing.JButton btnThree;
    private javax.swing.JButton btnTwo;
    private javax.swing.JButton btnZero;
    private javax.swing.JButton confirmBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextField firstNum;
    private javax.swing.JTextField infoFour;
    private javax.swing.JTextField infoOne;
    private javax.swing.JTextField infoThree;
    private javax.swing.JTextField infoTwo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel nowPlaying;
    private javax.swing.JTextField secondNum;
    private javax.swing.JTextField thirdNum;
    private javax.swing.JTextField totalBau;
    private javax.swing.JTextField totalBlank;
    private javax.swing.JTextField totalCure;
    private javax.swing.JTextField totalJoy;
    private javax.swing.JTextField totalMode;
    private javax.swing.JTextField totalNull;
    // End of variables declaration//GEN-END:variables
}
